name: Dependabot Auto-merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-merge:
    name: Auto-merge Dependabot PRs
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    
    steps:
      - name: Check PR Details
        id: pr-details
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const pr = context.payload.pull_request;
            const title = pr.title.toLowerCase();
            
            // Check if it's a patch or minor update
            const isPatch = title.includes('patch') || title.match(/bump .* from [\d.]+\d+ to [\d.]+\d+$/);
            const isMinor = title.includes('minor') && !title.includes('major');
            const isSecurity = title.includes('security') || pr.body.includes('security');
            
            // Auto-merge conditions
            const shouldAutoMerge = isPatch || (isMinor && !title.includes('breaking')) || isSecurity;
            
            return shouldAutoMerge ? 'true' : 'false';

      - name: Enable auto-merge for safe updates
        if: steps.pr-details.outputs.result == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE',
              body: '✅ Auto-approved by Dependabot workflow - safe dependency update detected.'
            });

      - name: Merge PR
        if: steps.pr-details.outputs.result == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              merge_method: 'squash',
              commit_title: context.payload.pull_request.title,
              commit_message: 'Automatically merged by Dependabot workflow'
            });

  security-check:
    name: Security Vulnerability Check
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run security audit
        run: npm audit --audit-level high
        
      - name: Check for critical vulnerabilities
        run: |
          CRITICAL_COUNT=$(npm audit --json 2>/dev/null | jq '.metadata.vulnerabilities.critical // 0')
          HIGH_COUNT=$(npm audit --json 2>/dev/null | jq '.metadata.vulnerabilities.high // 0')
          
          if [ "$CRITICAL_COUNT" -gt 0 ] || [ "$HIGH_COUNT" -gt 0 ]; then
            echo "❌ Critical or high vulnerabilities found!"
            echo "Critical: $CRITICAL_COUNT, High: $HIGH_COUNT"
            exit 1
          else
            echo "✅ No critical or high vulnerabilities found"
          fi

  notify-major-updates:
    name: Notify Major Updates
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    
    steps:
      - name: Check if major update
        id: major-check
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const title = context.payload.pull_request.title.toLowerCase();
            return title.includes('major') ? 'true' : 'false';

      - name: Add review request for major updates
        if: steps.major-check.outputs.result == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              reviewers: [context.repo.owner]
            });
            
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: `🚨 **Major Dependency Update Detected**
              
              This PR contains a major version update that may include breaking changes.
              Please review carefully before merging:
              
              - Check the changelog for breaking changes
              - Run tests locally if needed
              - Consider the impact on existing functionality
              
              **This PR will NOT be auto-merged** and requires manual review.`
            });
            
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              labels: ['major-update', 'needs-review']
            }); 